export const ACTIONS = {
  SET_HOME_DATA: "SET_HOME_DATA",
  DISPLAY_ALBUM_CONTENT: "DISPLAY_ALBUM_CONTENT",
  SET_PLAYLIST : "SET_PLAYLIST",
  SET_ARTIST: "SET_ARTIST",
  SET_SEARCH_QUERY: "SET_SEARCH_QUERY",
};
